### ISSUE TITLE
Release a compatible version with GHC 9.0

### ISSUE THREAD

**Issue by kakkun61** [serokell/haskell-with-utf8#12]
I am happy when 63b26842bec2da71f4b822d2dff14640e63a63e5 will be released!

Thanks!

**Comment by amesgen** [comment]
The library compiles fine with GHC 9.0, but the `utf8-troubleshoot` application depends on [`th-env`](https://hackage.haskell.org/package/th-env), which is not yet updated to GHC 9.0, and https://github.com/dzhus/th-env/pull/2, which fixes that, has not been merged yet.

Hence, a Hackage revision on `base` should be enough to make `with-utf8` usable on GHC 9.0 (without `allow-newer`).

**Comment by kirelagin** [comment]
Apologies, I somehow missed this issue. I guess now it makes sense to wait for 9.2.1 (#13) support and then release that.

**Comment by kirelagin** [comment]
All done and released: https://hackage.haskell.org/package/with-utf8-1.0.2.3 🎉
