### ISSUE TITLE
Update base dependency so it builds with `ghc-9.10`

### ISSUE THREAD

**Issue by erikd** [serokell/haskell-with-utf8#31]
In my `cabal.project` file I have:
```
allow-newer:
    with-uft8:base
```
Which allows my project to build.

This can be fixed with a Hackage metadata edit. I am a Hackage Trustee and can do this base bump if you would like me to,

**Comment by erikd** [comment]
PR is https://github.com/serokell/haskell-with-utf8/pull/32

**Comment by erikd** [comment]
Email sent to the most recent committer/maintainer.

**Comment by gromakovsky** [comment]
I have published a new revision: https://hackage.haskell.org/package/with-utf8-1.1.0.0/revisions/
